server:
  port: ${PORT:8080}

jwt:
  public-key: ${classpath:app.pub}
  private-key: ${classpath:app.key}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    url: "http://localhost:8080/"